#if !defined(INSN_DICT_H)
#define INSN_DICT_H
#define Iwhen_green_flag_clicked 1
#define Irepeat 2
#define Iforever 3
#define Iif_then 4
#define Iif_then_else 5
#define Iwait 6
#define Iwait_until 7
#define Irepeat_until 8
#define Ibreakpoint 9
#define Iplus 10
#define Iminus 11
#define Imultiply 12
#define Idivide 13
#define Imod 14
#define Iand 15
#define Ior 16
#define Inot 17
#define Iequal 18
#define Iless_than 19
#define Igreater_than 20
#define Iless_than_or_equal 21
#define Igreater_than_or_equal 22
#define Iround 23
#define Imath 24
#define Iturn_led 25
#define Iturn_dcmotor_on 26
#define Iturn_dcmotor_off 27
#define Ibuzzer_on 28
#define Ibuzzer_off 29
#define Iset_servomotor_degree 30
#define Iset_dcmotor_power 31
#define Imulti_led 32
#define Iservomotor_synchronized_motion 33
#define I3_axis_digital_accelerometer_value 34
#define Iir_photo_reflector_value 35
#define Ilight_sensor_value 36
#define Ibutton_value 37
#define Itouch_sensor_value 38
#define Ireset_timer 39
#define Itimer 40
#define Ipick_random 41
#define Ifunction 42
#define Icall_function 43
#define Ivariable 44
#define Ivariable_ref 45
#define Iset_variable_to 46
#define Ichange_variable_by 47
#define Ilist 48
#define Ilist_length 49
#define Ilist_add 50
#define Ilist_contains 51
#define Ilist_ref 52
#define Ilist_delete 53
#define Ilist_replace 54
#define Ilist_insert 55
#endif /* !defined(INSN_DICT_H) */
