#if !defined(STRING_DICT_H)
#define STRING_DICT_H
#define Swhen_green_flag_clicked 1
#define Srepeat 2
#define Sforever 3
#define Sif_then 4
#define Sif_then_else 5
#define Swait 6
#define Swait_until 7
#define Srepeat_until 8
#define Sbreakpoint 9
#define Splus 10
#define Sminus 11
#define Smultiply 12
#define Sdivide 13
#define Smod 14
#define Sand 15
#define Sor 16
#define Snot 17
#define Sequal 18
#define Sless_than 19
#define Sgreater_than 20
#define Sless_than_or_equal 21
#define Sgreater_than_or_equal 22
#define Sround 23
#define Smath 24
#define Sabs 25
#define Ssqrt 26
#define Ssin 27
#define Scos 28
#define Stan 29
#define Sln 30
#define Slog 31
#define Sec 32
#define S10c 33
#define Sturn_led 34
#define Sturn_dcmotor_on 35
#define Sturn_dcmotor_off 36
#define Sbuzzer_on 37
#define Sbuzzer_off 38
#define Sset_servomotor_degree 39
#define Sset_dcmotor_power 40
#define Smulti_led 41
#define Sservomotor_synchronized_motion 42
#define S3_axis_digital_accelerometer_value 43
#define Sir_photo_reflector_value 44
#define Slight_sensor_value 45
#define Sbutton_value 46
#define Stouch_sensor_value 47
#define Sreset_timer 48
#define Stimer 49
#define Spick_random 50
#define Sfunction 51
#define Scall_function 52
#define Svariable 53
#define Svariable_ref 54
#define Sset_variable_to 55
#define Schange_variable_by 56
#define Slist 57
#define Slist_length 58
#define Slist_add 59
#define Slist_contains 60
#define Slist_ref 61
#define Slist_delete 62
#define Slist_replace 63
#define Slist_insert 64
#endif /* !defined(STRING_DICT_H) */
